"""change main Booking model and create new BookingSeat model

Revision ID: A2
Revises: A1
Create Date: 2026-06-22 13:25:08.010034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'A2'
down_revision: Union[str, Sequence[str], None] = 'A1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_seats',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('booking_id', sa.Integer(), nullable=False),
                    sa.Column('seat_number', sa.String(
                        length=5), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['booking_id'], ['bookings.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('booking_id', 'seat_number',
                                        name='uq_booking_seats_booking_id_seat_number')
                    )
    op.drop_column('bookings', 'seat_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column(
        'seat_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('booking_seats')
    # ### end Alembic commands ###
