"""init flight and seat tables

Revision ID: Flight_1
Revises: 
Create Date: 2026-05-24 06:04:07.601925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'Flight_1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('flight_number', sa.String(
                        length=10), nullable=False),
                    sa.Column('departure_from', sa.String(
                        length=4), nullable=False),
                    sa.Column('arrival_to', sa.String(
                        length=4), nullable=False),
                    sa.Column('departure_time', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('arrival_time', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('price', sa.Numeric(
                        precision=10, scale=2), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_flights_flight_number'),
                    'flights', ['flight_number'], unique=False)
    op.create_table('seats',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('flight_id', sa.Integer(), nullable=False),
                    sa.Column('seat_number', sa.String(
                        length=5), nullable=False),
                    sa.Column('is_booked', sa.Boolean(), nullable=False),
                    sa.Column('locked_until', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['flight_id'], ['flights.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_seats_flight_id'), 'seats',
                    ['flight_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seats_flight_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_flights_flight_number'), table_name='flights')
    op.drop_table('flights')
    # ### end Alembic commands ###
