"""add/update models

Revision ID: Flight_2
Revises: Flight_1
Create Date: 2026-07-08 22:47:21.707174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'Flight_2'
down_revision: Union[str, Sequence[str], None] = 'Flight_1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_flights_departure_arrival', 'flights', [
                    'departure_from', 'arrival_to'], unique=False)
    op.drop_index(op.f('ix_seats_flight_id'), table_name='seats')
    op.create_unique_constraint('uq_flight_id_seat_number', 'seats', [
                                'flight_id', 'seat_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_flight_id_seat_number', 'seats', type_='unique')
    op.create_index(op.f('ix_seats_flight_id'), 'seats',
                    ['flight_id'], unique=False)
    op.drop_index('ix_flights_departure_arrival', table_name='flights')
    # ### end Alembic commands ###
